# Generated by cpp11: do not edit by hand

createFile <- function(filename, nEvent, nChannel, nSample, nDim, nCompressionRatio, is_libver_earliest) {
  .Call(`_ncdfFlow_createFile`, filename, nEvent, nChannel, nSample, nDim, nCompressionRatio, is_libver_earliest)
}

writeSlice <- function(filename, data, chIndx, sampleIndx, nRatio) {
  .Call(`_ncdfFlow_writeSlice`, filename, data, chIndx, sampleIndx, nRatio)
}

readSlice <- function(file, chIndx, sampleIndx) {
  .Call(`_ncdfFlow_readSlice`, file, chIndx, sampleIndx)
}
